<?php 
    include('header.php'); 
    
    if (isset($_GET['id']) && !empty($_GET['id'])) {
        $id = $_GET['id'];
    } else {
        header('Location: index.php');
        exit();
    }
?>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=Merriweather:wght@300;400;700&display=swap" rel="stylesheet">

<style>
    :root {
        --primary-color: #e63946;
        --text-dark: #111827;
        --text-body: #374151;
        --text-muted: #6b7280;
        --bg-light: #f9fafb;
        --card-radius: 12px;
    }

    body {
        background-color: var(--bg-light);
        font-family: 'Inter', sans-serif;
    }

    .news-detail-section {
        padding: 40px 0 80px;
    }

    /* --- Breadcrumb --- */
    .breadcrumb-nav {
        margin-bottom: 20px;
    }
    .back-link {
        color: var(--text-muted);
        text-decoration: none;
        font-size: 0.9rem;
        font-weight: 500;
        display: inline-flex;
        align-items: center;
        transition: color 0.2s;
    }
    .back-link:hover {
        color: var(--primary-color);
    }

    /* --- Main Article Styling --- */
    .article-container {
        background: #fff;
        padding: 40px; /* Generous padding */
        border-radius: var(--card-radius);
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
    }

    /* These styles target the HTML generated by your news_detail() function */
    .article-container h1, 
    .article-container .title {
        font-family: 'Inter', sans-serif;
        font-weight: 800;
        color: var(--text-dark);
        font-size: 2.2rem;
        line-height: 1.2;
        margin-bottom: 15px;
    }

    .article-container .date, 
    .article-container .meta {
        color: var(--text-muted);
        font-size: 0.9rem;
        margin-bottom: 25px;
        display: block;
        border-bottom: 1px solid #eee;
        padding-bottom: 20px;
    }

    /* The actual body text of the article */
    .article-container p,
    .article-container .description,
    .article-container .content {
        font-family: 'Merriweather', serif; /* Serif is better for long reading */
        font-size: 1.1rem;
        line-height: 1.8;
        color: var(--text-body);
        margin-bottom: 20px;
        overflow: auto;
        height: 500px;
    }

    /* Responsive Images inside the article */
    .article-container img {
        max-width: 100%;
        height: auto;
        border-radius: var(--card-radius);
        margin: 20px 0;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
    }

    /* --- Sidebar Styling --- */
    .sidebar-wrapper {
        /* Makes the sidebar sticky */
        position: -webkit-sticky;
        position: sticky;
        top: 20px; 
    }

    .sidebar-header {
        margin-bottom: 20px;
        position: relative;
        padding-left: 15px;
    }

    .sidebar-header::before {
        content: '';
        position: absolute;
        left: 0;
        top: 0;
        bottom: 0;
        width: 4px;
        background-color: var(--primary-color);
        border-radius: 2px;
    }

    .main-title {
        font-size: 1.25rem;
        font-weight: 700;
        color: var(--text-dark);
        margin: 0;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .relate-news {
        background: #fff;
        padding: 25px;
        border-radius: var(--card-radius);
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
    }

    /* Styles for content inside related_news() */
    .relate-news img {
        border-radius: 8px;
        width: 100%;
        height: auto;
        object-fit: cover;
    }
    
    .relate-news .item, 
    .relate-news .card {
        margin-bottom: 20px;
        border-bottom: 1px solid #f0f0f0;
        padding-bottom: 20px;
    }
    
    .relate-news .item:last-child {
        border-bottom: none;
        margin-bottom: 0;
        padding-bottom: 0;
    }

    .relate-news h3,
    .relate-news a,
    .relate-news a:visited {
        font-size: 1rem;
        font-weight: 600;
        color: #000;
        text-decoration: none;
        line-height: 1.4;
        transition: color 0.2s;
        margin-top: 10px;
        display: block;
    }

    .relate-news a:hover {
        color: var(--primary-color);
    }

    /* Mobile Adjustments */
    @media (max-width: 768px) {
        .article-container {
            padding: 20px;
        }
        .article-container h1 {
            font-size: 1.8rem;
        }
        .news-detail-section {
            padding-top: 20px;
        }
    }
</style>

<main class="news-detail-section">
    <div class="container">
        
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-nav">
                    <a href="index.php" class="back-link">
                        <i class="fa fa-arrow-left me-2"></i> Back to News
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 mb-4 mb-lg-0">
                <article class="article-container">
                    <?php news_detail($id); ?>
                </article>
            </div>

            <div class="col-lg-4 col-md-12">
                <aside class="sidebar-wrapper">
                    <div class="sidebar-header">
                        <h3 class="main-title">Related News</h3>
                    </div>
                    <div class="relate-news">
                        <?php related_news($id); ?>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</main>

<?php include('footer.php'); ?>